#██╗░██████╗██╗░░░░░░█████╗░███╗░░██╗██████╗░  ██████╗░██████╗░██╗██████╗░░██████╗░███████╗
#██║██╔════╝██║░░░░░██╔══██╗████╗░██║██╔══██╗  ██╔══██╗██╔══██╗██║██╔══██╗██╔════╝░██╔════╝
#██║╚█████╗░██║░░░░░███████║██╔██╗██║██║░░██║  ██████╦╝██████╔╝██║██║░░██║██║░░██╗░█████╗░░
#██║░╚═══██╗██║░░░░░██╔══██║██║╚████║██║░░██║  ██╔══██╗██╔══██╗██║██║░░██║██║░░╚██╗██╔══╝░░
#██║██████╔╝███████╗██║░░██║██║░╚███║██████╔╝  ██████╦╝██║░░██║██║██████╔╝╚██████╔╝███████╗
#╚═╝╚═════╝░╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░  ╚═════╝░╚═╝░░╚═╝╚═╝╚═════╝░░╚═════╝░╚══════╝
Prefix: "<##1DF4E9> &l● Bridge &8&l| "
